### ISSUE TITLE
Error: Fail to configure http client, error: "No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by prildy** [sendyhalim/lezeh#13]
Tried to run the binary from 0.8.0 and 0.8.1.
Environment mac os monterey 12.6
Both stumbled with this error whenever running
`lezeh deployment deploy`
and
`lezeh deployment merge-feature-branches`

I think the error should be related to internal code using http client. should I install one?

**Comment by sendyhalim** [comment]
Hi sorry for the confusion @prildy , I think it's highly probable related with the new config structure. It was a mistake, should've make it obvious that it's a breaking change 🙏 . https://github.com/sendyhalim/lezeh#setup
